### ISSUE TITLE
QR Code not generated at config.

### ISSUE THREAD

**Issue by raz0rf0x** [crealitycloud/OctoPrint-CrealityCloud#14]
Cannot register plugin with cloud app. At octoprint configuration screen there is no QR or manual code. Logs only show 
`
./GenerateIdentifier: error while loading shared libraries: libcurl.so: cannot open shared object file: No such file or directory`

https://model-admin2.creality.com/api/cxy/v2/common/getAddrress comes up as 404

**Comment by crealitycloud** [comment]
Try to run apt-get install curl and try again

**Comment by raz0rf0x** [comment]
I have installed it inside a clean debian container in a venv using directions from [here](https://community.octoprint.org/t/setting-up-octoprint-on-a-raspberry-pi-running-raspbian-or-raspberry-pi-os/2337) .

`curl --version

curl 7.64.0 (x86_64-pc-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3`

![image](https://user-images.githubusercontent.com/34667237/144697705-72d74173-02c5-4e0d-b71d-c0b454c0a1d3.png)

I get the same problem with the same error as above.

**Comment by raz0rf0x** [comment]
I was able to fix that error by running 
`sudo ln -s ./x86_64-linux-gnu/libcurl.so.4 /usr/lib/libcurl.so`

Now the error I get is 
`./GenerateIdentifier: option requires an argument -- 'a'`

**Comment by lllhy9428** [comment]
We have modified the way to bind the Crealitycloud. Now you can enjoy it！
