### ISSUE TITLE
无法获取QR code

### ISSUE THREAD

**Issue by bigtaotao** [crealitycloud/OctoPrint-CrealityCloud#21]
无法获取二维码，日志中报错
```
active_server.sh: line 3: ./GenerateIdentifier: No such file or directory
```
由于使用树莓派4b，可否编译AArch64版？或者公布源代码自行编译
祝好！

**Comment by hemiao218** [comment]
We are refactoring this part of the code.

**Comment by lllhy9428** [comment]
We have modified the way to bind the Crealitycloud. Now you can enjoy it！
