### ISSUE TITLE
How to get Creality Camera working?

### ISSUE THREAD

**Issue by Jiriteach** [crealitycloud/OctoPrint-CrealityCloud#23]
Hi - I have this installed and its working for the printer. I have a Creality camera. How do I get it working with this plugin?

Thanks

**Comment by hemiao218** [comment]
Creality camera only work with crealitybox now.

**Comment by Jiriteach** [comment]
Thanks. Does it work with Creality  - Raspberry Pi version?

**Comment by bilinxing** [comment]
try:[https://github.com/crealitycloud/OctoPrint-CrealityCloud-With-Video](https://github.com/crealitycloud/OctoPrint-CrealityCloud-With-Video)
