### ISSUE TITLE
Ender 3 S1 Pro not responding

### ISSUE THREAD

**Issue by TheFoxRanger** [crealitycloud/OctoPrint-CrealityCloud#47]
Hello,

My Ender 3 S1 Pro is connected to the Creality Cloud through a Raspberry Pi 3b+ (octoprint plugin). The Creality Cloud Android app shows the printer as "online" but it is not responding to any command (move bed, heat nozzle, etc...). What can I do to fix this ?

**Comment by crealitycloud** [comment]
Does the app show that the printer is connected?

**Comment by MettaUK** [comment]
Same problem, Ender3 S1 Pro, shows as connected in the App but it will not respond to controls and if I send a print via the App, nothing happens and after about 5 minutes ot shows as offline.

**Comment by TheFoxRanger** [comment]
> Does the app show that the printer is connected?

Yes !

**Comment by TheFoxRanger** [comment]
> Does the app show that the printer is connected?

**Comment by TheFoxRanger** [comment]
Yes

**Comment by TheFoxRanger** [comment]
Hello,

Yes the app shows a connected printer 

Le 17 juin 2022 à 07:52, à 07:52, Creality Cloud ***@***.***> a écrit:
>Does the app show that the printer is connected?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/crealitycloud/OctoPrint-CrealityCloud/issues/47#issuecomment-1158517043
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>
