### ISSUE TITLE
Creative Cloud plugin disabled

### ISSUE THREAD

**Issue by TTACsf** [crealitycloud/OctoPrint-CrealityCloud#71]
There  problem with the latest version of the plugin
[https://community.octoprint.org/t/creative-cloud-plugin-is-disabled/56938/2](url)
This is Octoprint's log
[octoprint-systeminfo-20240214223705.zip](https://github.com/crealitycloud/OctoPrint-CrealityCloud/files/14319298/octoprint-systeminfo-20240214223705.zip)

**Comment by bilinxing** [comment]
The latest version has fixed this issue
